// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZkSxkaPeEacPwFisuMYASXZaxcvNfGg0',
    appId: '1:57285740561:web:593c4e33a1142d1c6849b0',
    messagingSenderId: '57285740561',
    projectId: 'nikeapp-b119c',
    authDomain: 'nikeapp-b119c.firebaseapp.com',
    storageBucket: 'nikeapp-b119c.appspot.com',
    measurementId: 'G-LYTHX2W8RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23lwkNFNZiHIVxzsYekxv89vFp-lxvdc',
    appId: '1:57285740561:android:d170587c4cbe48f36849b0',
    messagingSenderId: '57285740561',
    projectId: 'nikeapp-b119c',
    storageBucket: 'nikeapp-b119c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtYke1Y67iG0Byq3HN1HvChl2nP5c16Ys',
    appId: '1:57285740561:ios:39006386f38734266849b0',
    messagingSenderId: '57285740561',
    projectId: 'nikeapp-b119c',
    storageBucket: 'nikeapp-b119c.appspot.com',
    iosBundleId: 'com.ratedsoltech.nikeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtYke1Y67iG0Byq3HN1HvChl2nP5c16Ys',
    appId: '1:57285740561:ios:39006386f38734266849b0',
    messagingSenderId: '57285740561',
    projectId: 'nikeapp-b119c',
    storageBucket: 'nikeapp-b119c.appspot.com',
    iosBundleId: 'com.ratedsoltech.nikeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZkSxkaPeEacPwFisuMYASXZaxcvNfGg0',
    appId: '1:57285740561:web:266362ab7563d47e6849b0',
    messagingSenderId: '57285740561',
    projectId: 'nikeapp-b119c',
    authDomain: 'nikeapp-b119c.firebaseapp.com',
    storageBucket: 'nikeapp-b119c.appspot.com',
    measurementId: 'G-M1V3D6J6FR',
  );
}
